### ISSUE TITLE
pyston-lite: SIGSEGV on aarch64 (aws graviton)

### ISSUE THREAD

**Issue by pwoolvett** [pyston/pyston_v2#305]
This follows from after applying the patch from #304 . As stated in that issue, the patch to discard dangerous JITted code via `DASM_CHECKS` works, but I am now getting a different kind of error(s?).

Next, some crash locations from different segfaults, which might share a common pattern:
```
    (Python) File "/usr/local/lib/python3.8/dist-packages/gevent/hub.py", line 166, in sleep
        hub.wait(t)
```

```
    (Python) File "/usr/local/lib/python3.8/dist-packages/yaml/resolver.py", line 117, in ascend_resolver
      Arguments:
        self: <CSafeLoader at 0x110ba400>
```

```
    (Python) File "/usr/lib/python3.8/types.py", line 178, in __get__
        return self.fget(instance)
```

```
    (Python) File "/usr/local/lib/python3.8/dist-packages/kafka/protocol/frame.py", line 13, in read
      Arguments:
        nbytes: 4
        self: <KafkaBytes at 0xffffa8ded2e0>
      Locals:
        start: 18220

```

Some additional thoughts:
* These code paths appear in several of the inspected core dumps, and correspond to either the last line of code within a function, or after a conditional return.
* A simple repro for the latest frame does not seem to trigger segfault.

Lib versions, for ref:
```
pyyaml==5.4.1
gevent==21.12.0
kafka-python==1.4.7
```
